# Generated by Django 2.1.1 on 2018-09-11 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktrading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField(max_length=1000)),
                ('review_author', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='owner_review',
        ),
        migrations.AddField(
            model_name='book',
            name='reviews',
            field=models.ManyToManyField(to='booktrading.Review'),
        ),
    ]
